run fix and add autologging ignore option
pinojs/pino-http pull request #153
Opened 2021-08-20 02:37 UTC by naseemkullah

solves #107 via a generic `autologging.ignore` function 

N.B I also ran `npm run fix` which linted the files.

2021-08-20 02:38 UTC, naseemkullah commented on logger.js
> +  const autoLoggingIgnore = opts.autoLogging && opts.autoLogging.ignore ? opts.autoLogging.ignore : null
here it starts

2021-08-20 02:38 UTC, naseemkullah commented on logger.js
> +        shouldLogSuccess = !isIgnored
and then here

2021-08-20 02:39 UTC, naseemkullah commented on test.js
> +test('no auto logging with autoLogging set to true and ignoring a specific user-agent', function (t) {
test here

2021-08-20 07:44 UTC, mcollina requested changes
Can you please restore all the spurious changes? There is a lot of var -> const/let migration here.

2021-08-20 17:14 UTC, naseemkullah commented
> Can you please restore all the spurious changes? There is a lot of var -> const/let migration here.

linting reverted, but tests fail locally (and in CI)

2021-08-20 22:43 UTC, mcollina approved these changes
lgtm

2021-08-21 16:56 UTC, mcollina commented
CI is failing because:

```
  /home/runner/work/pino-http/pino-http/logger.js:122:11: 'autoLoggingIgnore' is not defined.
61
  /home/runner/work/pino-http/pino-http/logger.js:123:27: 'autoLoggingIgnore' is not defined.
62
  /home/runner/work/pino-http/pino-http/logger.js:123:57: 'autoLoggingIgnore' is not defined.
```

2021-08-21 17:01 UTC, naseemkullah commented
> CI is failing because:
> 
> ```
>   /home/runner/work/pino-http/pino-http/logger.js:122:11: 'autoLoggingIgnore' is not defined.
> 61
>   /home/runner/work/pino-http/pino-http/logger.js:123:27: 'autoLoggingIgnore' is not defined.
> 62
>   /home/runner/work/pino-http/pino-http/logger.js:123:57: 'autoLoggingIgnore' is not defined.
> ```

Oops thanks, removed it when i reverted the linting, added back.

> CI is failing because:
> 
> ```
>   /home/runner/work/pino-http/pino-http/logger.js:122:11: 'autoLoggingIgnore' is not defined.
> 61
>   /home/runner/work/pino-http/pino-http/logger.js:123:27: 'autoLoggingIgnore' is not defined.
> 62
>   /home/runner/work/pino-http/pino-http/logger.js:123:57: 'autoLoggingIgnore' is not defined.
> ```

Oops, thanks. Fixing now.

2021-08-21 17:03 UTC, merged