Add custom object hooks
pinojs/pino-http pull request #231
Opened 2022-06-20 06:03 UTC by Simon-Campbell

This adds a functionality for overriding/customising the structured object logged at request received/success/error. It is *like* the custom[Received|Success|Error]Message hooks, but works on customising the structured object.

It was opted not to overload *Message due to that being specifically about messages, and the risk that adjusting that could break an existing usage of that hook.

The README has been updated with example usage.

2022-06-20 15:13 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2022-06-20 21:37 UTC, Simon-Campbell commented
> Thanks for opening a PR! Can you please add a unit test?

Thanks for feedback. I have now added tests as an extra commit.

2022-06-21 09:47 UTC, mcollina requested changes

2022-06-21 09:47 UTC, mcollina commented on logger.js
> +  const onRequestReceivedObject = opts.customReceivedObject && typeof opts.customReceivedObject === 'function' ? opts.customReceivedObject : undefined
Could you move the function to be a top-level function instead of a closure? I think the code would read better.

2022-06-21 09:47 UTC, mcollina commented on logger.js
> +          }
There are quite a a lot of conditionals in this block. Could you simplify them a bit and remove some duplications?

2022-06-26 03:02 UTC, Simon-Campbell commented
Hi @mcollina, 

I have addressed your feedback. I have also converted the common repeated pattern of (since I believe it further simplified what was being expressed.)

`const someEffectiveValue = opt.someOption && opt.someOption === 'function' ? opt.someOption : SomeDefaultOption;
`

to:

`
const someEffectiveValue = getFunctionOrDefault(opt.someOption, SomeDefaultOption);`

2022-06-26 19:23 UTC, mcollina approved these changes
lgtm

2022-06-26 19:24 UTC, merged