Fix customSuccessMessage ts definition
pinojs/pino-http pull request #270
Opened 2023-01-29 14:18 UTC by robmcguinness

https://github.com/pinojs/pino-http/pull/253 added `responseTime` value to be passed into the `customSuccessMessage` callback but the TS definition file was not updated.

2023-01-29 18:20 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test? For typescript we use tsd.

2023-01-29 18:22 UTC, robmcguinness commented
Whoops will do.

2023-01-29 21:28 UTC, robmcguinness commented
Added. Hopefully correct.

2023-01-30 11:22 UTC, mcollina approved these changes
lgtm

2023-01-30 11:27 UTC, merged