fix: twice customProps
pinojs/pino-http pull request #288
Opened 2023-06-11 01:29 UTC by youngkiu

Hello!
I am the author of [pino-web-hook](https://getpino.io/#/docs/transports?id=pino-slack-webhook).

I am using the NestJS framework, and I wanted to display the `pinoHttp` property, thinking that the main function of `nestjs-pino` is Middleware that connects `pino-http`.
```
    LoggerModule.forRoot({
      pinoHttp: {
        customProps: (req, res) => ({
          context: 'HTTP',
        }),
      },
    }),
```
However, I found the following bug, and also found out that there is an issue https://github.com/pinojs/pino-http/issues/216.
<img width="2471" alt="image" src="https://github.com/pinojs/pino-http/assets/13362880/74418d26-c366-455e-860f-26c63bee65e4">

I tried the following to solve this problem.
1. I tried to use [onchild-function](https://github.com/pinojs/pino/blob/master/docs/api.md#onchild-function), but stopped because the instance given as a parameter was a logger instance that could be known outside of OnChildCallback.
  ```js
+   opts.onChild = (instance) => {
+     // Execute call back code for each newly created child.
+   }
      const logger = wrapChild(opts, theStream)
  ```
2. The second method is the current PR. Additional conditional statements can be written on one line, but for readability, I have declared local variables.

Thanks

2023-07-21 16:02 UTC, jmealo commented
@youngkiu I thought this was by design to be fast... when the JSON is parsed, most parsers I have tested will keep the last entry logged, so there shouldn't be any dupes appearing in your log viewer?

2023-07-22 00:37 UTC, youngkiu commented
@jmealo Thanks for your interest in my fix.

I understand that using pino-pretty will output customProps without duplication due to JSON parsing.
Especially in the production log, I think it's more important to save it raw than to look pretty. - We plan to write a program that can analyze the accumulated logs if necessary in the future.
I don't use a separate JSON parser, but I modified it because duplicate logs were inconvenient.

2023-07-24 08:40 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2023-07-24 14:34 UTC, jmealo commented
@youngkiu: If you need a hand with unit tests let me know. I think a failing test for the current implementation would be the easiest way to approach this.

2023-07-24 22:47 UTC, youngkiu commented
@jmealo I'm still not sure how I was able to see `logger[chindingsSym]` in unit test. Can you help me write the test code?

2023-08-02 15:43 UTC, youngkiu commented
@mcollina 
In previous commit, customProps is number 2,
From my fix, I added a test case to ensure that customProps is number 1.
Please review PR

2023-08-02 16:54 UTC, mcollina approved these changes
lgtm

2023-08-03 18:04 UTC, jsumners approved these changes

2023-08-04 08:04 UTC, merged