fix: #308 include req.readableAborted flag to defaultSuccessfulRequestMessageProvider
pinojs/pino-http pull request #309
Opened 2023-11-20 10:20 UTC by someden

Closes #308

2023-11-20 19:25 UTC, mcollina requested changes
Thanks for opening a PR! Can you please add a unit test?

2023-11-29 19:40 UTC, someden commented
@mcollina done

2023-12-26 10:43 UTC, mcollina commented
A test is failing on node v14

2023-12-26 13:42 UTC, someden commented
@mcollina, do you have some plans to drop node v14 support?

2023-12-26 14:40 UTC, mcollina commented
Of course, might actually be time to drop v14 and v16.

2023-12-26 18:36 UTC, mcollina commented
Could you remove them from CI? I will bump the major.

2023-12-27 13:11 UTC, mcollina commented on .github/workflows/ci.yml
> +        node-version: [18]
```suggestion
        node-version: [18, 20, 21]
```

2023-12-27 21:48 UTC, mcollina approved these changes
lgtm

2023-12-27 22:16 UTC, merged